services:

  client:
    container_name: client
    image: client
    build:
      context: .
      target: client
    init: true
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1

  mitm:
    container_name: mitm
    image: mitm
    build:
      context: .
      target: mitm
    init: true
    volumes:
      - ./:/app/:rw
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    sysctls:
      net.ipv4.ip_forward: 1
